const setting = {
  publicPath: '',
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: true,
  transpileDependencies: ['vue-echarts', 'resize-detector'],
  baseURL:
    process.env.NODE_ENV === 'development' ? 'http://127.0.0.1:8000' : 'http://127.0.0.1:8000',
  title: 'SUNTECH VIỆT NAM',
  titleSeparator: ' - ',
  titleReverse: false,
  abbreviation: 'vab-pro',
  devPort: '9999',
  version: process.env.VUE_APP_VERSION,
  copyright: 'chuzhixin 1204505056@qq.com',
  keepAliveMaxNum: 99,
  routerMode: 'hash',
  routesWhiteList: ['/login', '/register', '/callback', '/404', '/403'],
  loadingText: 'Loading...',
  tokenName: 'accessToken',
  tokenTableName: 'accessToken',
  storage: 'localStorage',
  recordRoute: true,
  logo: 'vuejs-fill',
  i18n: 'zh',
  errorLog: ['development', 'production'],
  loginInterception: true,
  loginRSA: false,
  authentication: 'intelligence',
  rolesControl: true,
  uniqueOpened: false,
  defaultOpeneds: ['/vab'],
  debounce: ['doEdit'],
  providePlugin: {},
  build7z: false,
  templateFolder: 'project',
  donation: false,
  openFirstMenu: true,
}

module.exports = setting
